### ISSUE TITLE
容器运行，编译出错

### ISSUE THREAD

**Issue by hyfsy** [hyfsy/hot-refresh#4]
2022-05-26 10:16:11 [DEBUG] com.hyf.hotrefresh.core.exception.RefreshException: Hot refresh failed
	at com.hyf.hotrefresh.core.refresh.HotRefresher.refresh(HotRefresher.java:69)
	at com.hyf.hotrefresh.core.remoting.handler.RpcHotRefreshRequestHandler.handle(RpcHotRefreshRequestHandler.java:40)
	at com.hyf.hotrefresh.core.remoting.handler.RpcHotRefreshRequestHandler.handle(RpcHotRefreshRequestHandler.java:19)
	at com.hyf.hotrefresh.remoting.message.handler.AbstractMessageHandler.handle(AbstractMessageHandler.java:37)
	at com.hyf.hotrefresh.remoting.server.HotRefreshServer.handle(HotRefreshServer.java:44)
	at com.hyf.hotrefresh.adapter.web.HotRefreshFilter.doFilter(HotRefreshFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke$original$bqXEqo3P(StandardHostValve.java:139)
	at org.apache.catalina.core.StandardHostValve.invoke$original$bqXEqo3P$accessor$qa6W19QX(StandardHostValve.java)
	at org.apache.catalina.core.StandardHostValve$auxiliary$q3gUNN7R.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalStateException: Cannot load JavaCompiler, please confirm the application running in JDK not JRE.
	at com.hyf.hotrefresh.core.memory.MemoryCodeCompiler.compile(MemoryCodeCompiler.java:49)
	at com.hyf.hotrefresh.core.memory.MemoryCodeCompiler.compile(MemoryCodeCompiler.java:39)
	at com.hyf.hotrefresh.core.refresh.HotRefresher.refresh(HotRefresher.java:32)
	... 39 more

**Comment by hyfsy** [comment]
cann't emersion, ignored
