### ISSUE TITLE
新建文件后直接报错

### ISSUE THREAD

**Issue by hyfsy** [hyfsy/hot-refresh#7]
2022-07-22 19:09:23 [DEBUG] java.lang.RuntimeException: Read input stream failed
	at com.hyf.hotrefresh.remoting.rpc.payload.RpcRequest.encode(RpcRequest.java:50)
	at com.hyf.hotrefresh.core.remoting.payload.RpcHotRefreshRequest.encode(RpcHotRefreshRequest.java:35)
	at com.hyf.hotrefresh.remoting.rpc.payload.RpcBatchMessage.encode(RpcBatchMessage.java:39)
	at com.hyf.hotrefresh.remoting.message.MessageCodec.encode(MessageCodec.java:60)
	at com.hyf.hotrefresh.client.core.DefaultRequestBuilder.build(DefaultRequestBuilder.java:34)
	at com.hyf.hotrefresh.client.core.rpc.RpcClient.sync(RpcClient.java:94)
	at com.hyf.hotrefresh.client.core.rpc.RpcClient.sync(RpcClient.java:64)
	at com.hyf.hotrefresh.client.core.HotRefreshClient.sendMessage(HotRefreshClient.java:53)
	at com.hyf.hotrefresh.client.core.HotRefreshClient.sendBatchRequest(HotRefreshClient.java:48)
	at com.hyf.hotrefresh.client.core.rpc.RpcPushWatcher.handleFileChangeRequest(RpcPushWatcher.java:96)
	at com.hyf.hotrefresh.client.core.rpc.RpcPushWatcher.run(RpcPushWatcher.java:58)
Caused by: java.nio.file.NoSuchFileException: E:\study\code\idea3\learn-springboot\learn-springboot-initializr-jar\src\main\java\com\hyf\hello\execute\HotDetectExecute.java
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at com.hyf.hotrefresh.client.core.DeferredOpenFileInputStream.ensureOpen(DeferredOpenFileInputStream.java:89)
	at com.hyf.hotrefresh.client.core.DeferredOpenFileInputStream.read(DeferredOpenFileInputStream.java:39)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.hyf.hotrefresh.common.util.IOUtils.writeTo(IOUtils.java:34)
	at com.hyf.hotrefresh.common.util.IOUtils.readAsByteArray(IOUtils.java:15)
	at com.hyf.hotrefresh.remoting.rpc.payload.RpcRequest.encode(RpcRequest.java:47)
	... 10 more

**Comment by hyfsy** [comment]
see [1438664](https://github.com/hyfsy/hot-refresh/commit/1438664bd22d1149c425b54e9e33a9cd6824b30b)
